import {button} from "./mixins/button-mixin.js";
import {form} from "./mixins/form-mixin.js";
import {list} from "./list.js";

webix.ui({
    cols:[
        list,
        {
           view: "autoGeneratedForm",
           id: "form",
           //fields: ["Fname", "Lname", "Address" ],
           saveAction: function(){
               console.log("save");
           },
           clearAction: function(){
               console.log("clear");
           }
        }
    ]
});