export const form = webix.protoUI({
    name:"autoGeneratedForm",
    $init: function (config) {
        if(!config.fields || !Array.isArray(config.fields)){
            webix.message({
                text:"Form fields are undefined",
                type:"error", 
                expire: 1000,
            });
            config.elements = [];
        }else{
            config.elements = this._setFields(config);
        }
        
    },
    _setFields: function(config) {
        const elements = [];
        config.fields.forEach(function(item) {
            elements.push({ view: "text", label: `${item}`, name: `${item}`});
        });
        elements.push({cols: [
            { 
                view: "button", 
                value: "Cancel",
                inputWidth: 200,
                click: config.clearAction || this.defaults.clearAction
            }, 
            { 
                view: "button", 
                value: "Save",
                inputWidth: 200,
                css: "webix_primary",
                align: "right",
                click: config.saveAction || this.defaults.saveAction
            }
        ]});
        return elements;
    },
    defaults:{
       saveAction: function() {
                    webix.message({
                        text:"Form is saved",
                        type:"info", 
                        expire: 1000,
                    })},
       clearAction: function() {
                    webix.message({
                        text:"Form is cleared",
                        type:"info", 
                        expire: 1000,
                    })},
    }

}, webix.ui.form);